services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh django-entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: always

  celery:
    build:
      context: .
      dockerfile: celery_dockerfile
    command: sh celery-entrypoint.sh
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      - web

  postgres_db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 3

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    command: minio server /data

  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    env_file:
      - .env
    volumes:
      - redis_insight_volume_data:/db

volumes:
  postgres_data:
    driver: local
  redis_volume_data:
  redis_insight_volume_data:
