# Generated by Django 5.1.1 on 2024-10-09 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Номер билета"
                    ),
                ),
                (
                    "transport_id",
                    models.CharField(max_length=20, verbose_name="Номер ТС"),
                ),
                ("payment_date", models.DateField(verbose_name="Дата покупки")),
                ("payment_time", models.TimeField(verbose_name="Время")),
                ("registration_sign", models.CharField(verbose_name="Рег. Знак")),
                ("qr_token", models.TextField(verbose_name="Токен из QR-кода")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, выгрузивший токен",
                    ),
                ),
            ],
        ),
    ]
