# Generated by Django 5.1.1 on 2024-11-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature_toggles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuretoggle",
            name="description",
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
    ]
