# Generated by Django 5.1.1 on 2024-11-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature_toggles", "0002_featuretoggle_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuretoggle",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
